### ISSUE TITLE
Secure Runtime Secrets Decryption in Container Entrypoint Using SOPS and Azure Key Vault

### ISSUE THREAD

**Issue by daveman1010221** [cmu-sei/Polar#45]
## Summary

Implement a secure secrets management flow that uses SOPS-encrypted secrets stored in Git and decrypts them at runtime using the container's assigned identity to authenticate with Azure Key Vault. This ensures that decrypted secrets never appear in CI/CD or Git history, and are only accessible to the container process in-memory.

This improves overall secrets hygiene, supports key rotation with zero downtime, and aligns with Zero Trust and GitOps security principles.

## Goals

* Prevent decrypted secrets from being exposed in CI/CD or Git
* Use Azure-managed identity for secure, credential-less access to Key Vault
* Integrate secret decryption into the container’s entrypoint
* Maintain encrypted secret artifacts in version control (for auditability)

```mermaid
sequenceDiagram
    participant Dev as Developer
    participant Git as Git Repository (Encrypted Secrets)
    participant CI as CI Pipeline (GitLab, etc.)
    participant Image as Container Image (with entrypoint)
    participant K8s as Kubernetes Cluster (AKS)
    participant Pod as Container (Pod)
    participant Vault as Azure Key Vault
    participant AAD as Azure AD (Identity Provider)
    
    Dev->>Git: Commit SOPS-encrypted secrets\n(e.g., secrets.enc.yaml)
    Git-->>CI: Push triggers build
    CI->>Image: Build container image\n(+ entrypoint script, sops binary)
    CI-->>Git: Does not decrypt secrets
    CI->>Registry: Push container image
    Git-->>K8s: Flux/Argo applies manifests\n(includes encrypted secrets)
    K8s->>Pod: Start container from image
    
    activate Pod
    Note right of Pod: Entrypoint script runs

    Pod->>AAD: Request token\n(via MSI or OIDC federation)
    AAD-->>Pod: Return identity token (JWT or MSI token)

    Pod->>Vault: Request decryption\n(using identity token)
    Vault-->>Pod: Return decrypted KEK (key encryption key)

    Pod->>Pod: Run `sops -d secrets.enc.yaml`\nwith KEK from Key Vault
    Pod->>Pod: Inject secrets into env or memory
    Pod->>Pod: Exec main application binary

    deactivate Pod

    Note over Pod: Secrets only exist\nin memory during runtime
```

### Directory Layout
```
my-container/
├── Dockerfile
├── entrypoint.sh
├── .sops.yaml
├── secrets/
│   └── app-secrets.enc.yaml
└── app/
    └── my-app-binary
```

### Sample Dockerfile
```dockerfile
FROM alpine:3.19

RUN apk add --no-cache bash curl gnupg sops jq

COPY entrypoint.sh /entrypoint.sh
COPY .sops.yaml /.sops.yaml
COPY secrets/ /secrets/
COPY app/ /app/

ENTRYPOINT ["/entrypoint.sh"]
```

### .sops.yaml
```yaml
creation_rules:
  - path_regex: "secrets/.*\\.enc\\.yaml$"
    encrypted_regex: '^(data|stringData)$'
    azure_keyvault:
      vault_url: https://my-vault-name.vault.azure.net
      key_name: my-sops-key
      client_id: 00000000-0000-0000-0000-000000000000  # Optional for workload identity
```

Entrypoint script
```bash
#!/bin/bash
set -eo pipefail

SECRET_FILE="/secrets/app-secrets.enc.yaml"

echo "[+] Decrypting secrets with SOPS..."
DECRYPTED_SECRETS=$(sops -d "$SECRET_FILE")

echo "[+] Parsing and exporting secrets into environment..."
echo "$DECRYPTED_SECRETS" | jq -r '.stringData | to_entries[] | "export \(.key)=\(.value)"' > /tmp/secrets.env
source /tmp/secrets.env
rm -f /tmp/secrets.env

echo "[+] Launching application..."
exec /app/my-app-binary
```

###  Example SOPS-encrypted Secret File (secrets/app-secrets.enc.yaml)
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
stringData:
  DATABASE_URL: postgres://user:pass@db:5432/app
  JWT_SECRET: supersecretjwtkey
```

For example:

```
sops -e -i secrets/app-secrets.enc.yaml
```

### Azure Key Vault Setup
* Ensure your managed/workload identity has access to the Key Vault and my-sops-key:
   * Role: Key Vault Crypto User or Key Vault Secrets User
* If using Workload Identity, annotate the pod:

```yaml
metadata:
  annotations:
    azure.workload.identity/client-id: <client-id>
```

### Tasks for Runtime Secrets Decryption Integration

- [x] Create `.sops.yaml` with Azure Key Vault key reference
- [ ] Encrypt secret files with `sops -e`
- [ ] Build `entrypoint.sh` that decrypts and injects secrets
- [ ] Update container `Dockerfile` to include all necessary tools
- [ ] Annotate Kubernetes pods or service accounts for workload identity
- [ ] Test full runtime decryption flow
- [ ] Document key rotation process and secret update workflow

### Future Considerations
* Replace direct environment injection with tmpfs-based file mapping
* Implement secret lifecycle observability and rotation metrics
* Optionally support fetching encrypted secrets from a remote store (e.g., S3, Git submodule)
