### ISSUE TITLE
Polar Policy Agent Proposal

### ISSUE THREAD

**Issue by vonjackets** [cmu-sei/Polar#54]
We need an agent capable of managing policy enforcement and deployment management for our services.

Mainly this work should serve to make the services pretty configurable, without constraining the data pipeline. We want to be greedy with the data we pull out from other systems so we can put it all in the graph. When it comes to access control, systems like gitlab can limit what the observer can see through tokens. 

Neo4j doesn’t emit events when new data is inserted. So we need to detect pipeline failures as _new_ events, even if they were added via a bulk sync. In addition we can get cluster state and historical data from Neo4j to unlock "policy as analytics" capabilities.

- Initial configuration will use policies defined via YAML (or Dhall) against this data.
- Policies can also outline how to respond to  deployment events using the k8s API (`kube-rs`) such as rollbacks and deployment failures. 
## Example YAML Policy: Deployment-Aware

```yaml
type: "Deployment Failure"
match:
  status: "failed"
  since: "1h"
  branch: "main"

actions:
  - type: "notify"
    method: "slack"
    channel: "#deployments"
    template: "main-deploy-failed"

  - type: "rollback"
    target: "deployment/polar-api"
    strategy: "previous-image"

  - type: "scale"
    resource: "deployment/polar-worker"
    replicas: 0

  - type: "restart"
    resource: "deployment/polar-web"

  - type: "annotate"
    resource: "deployment/polar-api"
    key: "polar.io/failure-reason"
    value: "pipeline failure on {{ timestamp }}"
```

This agent will run separately from the Kubernetes observer and focus purely on decision-making and action based on observed trends and state.

---

## Deliverables

- [ ] A service that:
  - [ ] Reads yaml policy configurations from a given git repository for its source of truth.
  - [ ] Queries Neo4j for recent cluster state.
  - [ ] Applies policies and updates to observer/consumer pairs through cassini.
  - [ ] Responds to deployment events (e.g., detect high pod restart rates, failed deployments, out-of-sync replicas).
  - [ ] Takes basic Kubernetes actions (pod restart, scale, etc.) to assist failed deployments                           
  - [ ] Emits notification events on important triggers.

- [ ] Config Schema:
  - Define what a "policy" looks like in YAML (start simple: matching on Deployment name, namespace, event type, thresholds).
  
---

## Guidance

- **Greedy Observation Model:**  
  The observer already captures available cluster data. The policy agent should not filter what data is collected — it only decides how to *react*. Rust and Cynic demand explicit graphql queries, so allowing others to "color outside the lines" would require that we relax our control over the data.                        

- **Simplicity First:**  
  We could start with **few, hardcoded** policies for validation. Evolve config syntax later after user feedback.

- **Kubernetes Abstraction:**  
  Per our rendered manifests strategy, users should **never need to directly manipulate Kubernetes manifests.  
  Policy = *Intent*, Agent = *Action*.

- **Failure Resilience:**  
  The agent must be able to detect and handle partial failures gracefully (e.g., a rollout fails halfway).
